sudo: false
language: go

go:
  - "stable"
  - "1.10.4"
  - "1.9.x"
  - "1.8.x"
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_script:
  - go get -u golang.org/x/lint/golint

script:
  - go test -v --race ./...

after_script:
  - test -z "$(gofmt -s -l -w . | tee /dev/stderr)"
  - test -z "$(golint ./...     | tee /dev/stderr)"
  - go vet ./...

os:
  - linux
  - osx

notifications:
  email: false
